//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meal
    {
        public int MealId { get; set; }
        public int StudentId { get; set; }
        public System.DateTime MealDate { get; set; }
        public int Lunch { get; set; }
        public int Dinner { get; set; }
        public int LunchGuestMeal { get; set; }
        public int DinnerGuestMeal { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
