//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealInfo
    {
        public int MealInfoId { get; set; }
        public int StudentId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool LunchOff { get; set; }
        public bool DinnerOff { get; set; }
        public Nullable<int> LunchGuestMeal { get; set; }
        public Nullable<int> DinnerGuestMeal { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
