//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Expenses = new HashSet<Expense>();
            this.Meals = new HashSet<Meal>();
            this.MealInfoes = new HashSet<MealInfo>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int StudentId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int DeptId { get; set; }
        public string Batch { get; set; }
        public string RoomNo { get; set; }
        public string MobileNo { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string IsApproved { get; set; }
        public string Role { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<Expense> Expenses { get; set; }
        public virtual ICollection<Meal> Meals { get; set; }
        public virtual ICollection<MealInfo> MealInfoes { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
